[2023-06-16T09:40:06.455233+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /var/www/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-06-16T09:52:19.488944+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /var/www/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-06-16T09:53:58.807933+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /var/www/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-06-16T09:58:45.170730+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /var/www/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-06-16T09:58:45.186684+00:00] php.DEBUG: Warning: mkdir(): File exists {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/vendor/symfony/cache/Traits/FilesystemCommonTrait.php","line":123,"trace":[{"file":"/var/www/vendor/symfony/cache/Adapter/PhpFilesAdapter.php","line":246,"function":"getFile","class":"Symfony\\Component\\Cache\\Adapter\\PhpFilesAdapter","type":"->"}],"count":1}}} []
[2023-06-16T09:58:45.193047+00:00] php.DEBUG: Warning: mkdir(): File exists {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/vendor/symfony/cache/Traits/FilesystemCommonTrait.php","line":123,"trace":[{"file":"/var/www/vendor/symfony/cache/Adapter/PhpFilesAdapter.php","line":246,"function":"getFile","class":"Symfony\\Component\\Cache\\Adapter\\PhpFilesAdapter","type":"->"}],"count":1}}} []
[2023-06-16T09:58:45.230752+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-16T09:58:45.230836+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-16T09:58:45.293760+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-16T09:58:45.293770+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-16T09:58:45.297242+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "db" (172.31.0.2), port 5433 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2023-06-16T09:58:45.297287+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "db" (172.31.0.2), port 5433 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2023-06-16T12:16:30.967234+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-16T12:16:31.056054+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-16T12:16:31.062770+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "db" (172.31.0.4), port 5433 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.4), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.4), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.4), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2023-06-18T10:18:07.067370+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:803/lottery"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:803/lottery\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lottery/\". at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2023-06-18T10:18:33.073509+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-18T10:18:33.161044+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5433,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-18T10:18:33.164120+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "db" (172.31.0.2), port 5433 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"db\" (172.31.0.2), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /var/www/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:34)"} []
[2023-06-18T10:19:55.828850+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-18T10:19:55.922909+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-18T10:19:55.937589+00:00] doctrine.DEBUG: Executing query: SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC {"sql":"SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC"} []
[2023-06-18T10:19:55.943909+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "team" does not exist LINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...                                                              ^" at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 7): An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"team\" does not exist\nLINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...\n                                                             ^ at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:71)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"team\" does not exist\nLINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...\n                                                             ^ at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"team\" does not exist\nLINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...\n                                                             ^ at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:70)"} []
[2023-06-18T10:19:56.033309+00:00] doctrine.INFO: Disconnecting [] []
[2023-06-18T10:19:57.500622+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-18T10:19:57.503985+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-18T10:19:57.511845+00:00] doctrine.DEBUG: Executing query: SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC {"sql":"SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC"} []
[2023-06-18T10:19:57.512996+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "team" does not exist LINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...                                                              ^" at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 7): An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"team\" does not exist\nLINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...\n                                                             ^ at /var/www/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:71)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"team\" does not exist\nLINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...\n                                                             ^ at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"team\" does not exist\nLINE 1: ...created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ O...\n                                                             ^ at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:70)"} []
[2023-06-18T10:19:57.577877+00:00] doctrine.INFO: Disconnecting [] []
[2023-06-18T10:21:14.131941+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-18T10:21:14.136796+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-18T10:21:14.145542+00:00] doctrine.DEBUG: Executing query: SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC {"sql":"SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC"} []
[2023-06-18T10:21:14.181046+00:00] doctrine.INFO: Disconnecting [] []
[2023-06-18T10:21:28.761954+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:803/lottery"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:803/lottery\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lottery/\". at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2023-06-18T10:21:41.210437+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:803/lottery"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:803/lottery\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lottery/\". at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2023-06-18T10:21:58.614334+00:00] request.INFO: Matched route "api_team_rank". {"route":"api_team_rank","route_parameters":{"_route":"api_team_rank","_controller":"App\\Controller\\TeamController::teamsByRankWithOdds"},"request_uri":"http://localhost:803/team/rank","method":"GET"} []
[2023-06-18T10:21:58.619000+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"} {"params":{"driver":"pdo_pgsql","host":"db","port":5432,"user":"testUser","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"nba","serverVersion":"14","charset":"utf8"}} []
[2023-06-18T10:21:58.629526+00:00] doctrine.DEBUG: Executing query: SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC {"sql":"SELECT t0_.id AS id_0, t0_.name AS name_1, t0_.victory AS victory_2, t0_.rank AS rank_3, t0_.created_at AS created_at_4, t0_.updated_at AS updated_at_5 FROM team t0_ ORDER BY t0_.rank DESC"} []
[2023-06-18T10:21:58.638799+00:00] doctrine.INFO: Disconnecting [] []
[2023-06-18T10:22:30.962294+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST http://localhost:803/lottery"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST http://localhost:803/lottery\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lottery\". at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2023-06-18T10:22:47.771742+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST http://localhost:803/lottery"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST http://localhost:803/lottery\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lottery\". at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2023-06-18T10:28:54.175805+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:803/lottery"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:803/lottery\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lottery/\". at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
[2023-06-18T10:28:54.656035+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:803/lottery"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:803/lottery\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lottery/\". at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
